# ----------- CONFIGURABLE START -----------
title:            "Localization team offical website"
description:      "To see more people and more project"
url:              http://sumin.ink # 域名
signoff:          "Su Min" # Your name
facebook_appid:   #sumin1123
google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 15
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         首页
    url:          /
    external:     false
  - name:         简介
    url:          /book
    external:     false
  - name:         项目
    url:          /road
    external:     false
  - name:         归档
    url:          /archives
    external:     false
  - name:         标签
    url:          /tags
    external:     false
  - name:         关于
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
